### ISSUE TITLE
shape of buf maybe wrong?

### ISSUE THREAD

**Issue by archershot** [rahul-goel/fused-ssim#6]
https://github.com/rahul-goel/fused-ssim/blob/d99e3d27513fa3563d98f74fcd40fd429e9e9b0e/ssim.cu#L132

as shown above, both local_x and local_y are in [5, 5+32).  So, opt should has the shape of [42, 42]. Otherwise, this and later should be opt[local_y][local_x-5] = val.

**Comment by rahul-goel** [comment]
Hi.

Thanks for diving deep into the code and bringing this to my notice. I'm surprised to not obtain an error due to this now. It has been fixed now.

Thanks
