### ISSUE TITLE
TORCH_USE_CUDA_DSA

### ISSUE THREAD

**Issue by chenqi13814529300** [rahul-goel/fused-ssim#7]
Training progress:   0%|          | 80/30000 [00:02<13:19, 37.41it/s, Loss=1.0910213, Depth Loss=0.2243882]
Training progress:   0%|          | 90/30000 [00:02<13:14, 37.65it/s, Loss=1.0910213, Depth Loss=0.2243882]Traceback (most recent call last):
  File "E:\GSproject\gs\gaussian-splatting\train.py", line 755, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations,
  File "E:\GSproject\gs\gaussian-splatting\train.py", line 563, in training
    loss.backward()
  File "E:\conda\envs\3dgs\lib\site-packages\torch\_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "E:\conda\envs\3dgs\lib\site-packages\torch\autograd\__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "E:\conda\envs\3dgs\lib\site-packages\torch\autograd\function.py", line 288, in apply
    return user_fn(self, *args)
  File "E:\conda\envs\3dgs\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 155, in backward
    grad_means2D, grad_colors_precomp, grad_opacities, grad_means3D, grad_cov3Ds_precomp, grad_dc, grad_sh, grad_scales, grad_rotations = _C.rasterize_gaussians_backward(*args)
RuntimeError: CUDA error: invalid configuration argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by rahul-goel** [comment]
Hi.

I'm not sure whether this issue is due to the fused-ssim implementation or this is an error due to the gaussian splatting rasterization backend that you're using. From your log, I see that the training happened for 90 iterations already. And since image size remains same during training, SSIM most likely should not cause an error in later iterations if it was successful in the first few ones.

Please can you elaborate more.

**Comment by chenqi13814529300** [comment]
The current issue is that when I use：
pip uninstall diff-gaussian-rasterization -y
cd submodules/diff-gaussian-rasterization
rm -r build
git checkout 3dgs_accel
pip install .

**Comment by chenqi13814529300** [comment]
I have segmented the large scene and also segmented the laser point cloud. For example, if 10 blocks are divided, about 5 of them can correctly complete 30000 rounds. But there were 5 times when an error was reported like this. An error occurred after several iterations. My computer is Windows 11

**Comment by chenqi13814529300** [comment]
https://github.com/graphdeco-inria/gaussian-splatting/issues/1080

**Comment by chenqi13814529300** [comment]
I think your rasterization speed is excellent, but there are bugs. My personal level is relatively low, and I hope the experts can fix it as soon as possible！

**Comment by chenqi13814529300** [comment]
https://github.com/rahul-goel/fused-ssim/issues/6    
I guess this might solve my problem? I will test it first and provide feedback once I have the results.

**Comment by chenqi13814529300** [comment]
![image](https://github.com/user-attachments/assets/fc0026ac-cb0c-41f3-af6a-0996a1dfcb3c)
After modification, uninstalling and reinstalling still produces an error message

**Comment by BitCalSaul** [comment]
@rahul-goel hi im wondering if you will fix this issue. Same issue here.

**Comment by BitCalSaul** [comment]
@rahul-goel Thanks for your work. I just want to confirm my understanding: the issue might stem from the additional loss implemented in the original GraphDECO codebase, whereas it doesn't appear in the TAMING-GS rasterizer. So, if I want to experiment with the backward optimization from TAMING-GS, I can directly use the rasterizer provided in this repository, correct?
